### PR TITLE
0.2.0 release

### PR DESCRIPTION
**Pull request by rcrowe**
A lot has been re-written, simplified & tests added.

### CODE REVIEW

**Comment by rcrowe** [comment]
Yep. I should get a chance to update 0.2.x and merge / tag soon. Sorry in the delay!

**Comment by stayallive** [comment]
I am running `"rcrowe/raven": "dev-release/0.2.0"` for a while (read 1-2 months) now and am pretty satisfied! (Oh, and yes this is in production :grin:)

**Comment by rcrowe** [comment]
Great! I always worry when it's just me running it in production & I'm not covering all edge cases.

I've bumped the Guzzle dependency up to ~4.1.0 which means that the library is now >=php5.4. Does that impact you @Stayallive?

**Comment by stayallive** [comment]
Laravel 4.2 is also >= 5.4 so yeah I'm cool with that :) I usually jump versions pretty quick ;)

**Comment by stayallive** [comment]
@coveralls sure likes to spam! geez!

Off topic: Could be nice if they would do it like Travis :)

**Comment by rcrowe** [comment]
Bloody hell, @coveralls went nuts. I think I'll just push a lot less often, sorry about that :)

**Comment by rcrowe** [comment]
So I just tagged `0.2.0` let us know if you spot anything!

**Comment by stayallive** [comment]
Looks good so far!

**Pull request merged**
